import type { Metadata } from "next";
import { ArrowRight, Database, Github, KeyRound, LockKeyhole, RadioTower, Server, ShieldCheck, Wifi } from "lucide-react";
import { MarketingCta } from "@/components/marketing-shell";

export const metadata: Metadata = { title: "Security", description: "How Agent God Mode protects credentials and connects GitHub, Paseo, Supabase, and durable workflows." };

export default function SecurityPage() {
  return <main className="marketing-subpage"><section className="marketing-page-hero"><span className="marketing-kicker">Security and infrastructure</span><h1>Operational visibility without putting secrets in the browser.</h1><p>Agent God Mode separates the control-plane data your interface needs from the credentials used to reach GitHub and Paseo.</p></section>
    <section className="security-boundary"><div className="marketing-section-heading"><span>Clear boundaries</span><h2>The browser sees state. Server-side workflows hold capabilities.</h2></div><div className="boundary-diagram"><article><span>Browser-visible</span><h3>Operational data</h3><ul><li>Workstreams and branches</li><li>Plans and annotations</li><li>Timelines and questions</li><li>Review findings and status</li></ul></article><div><LockKeyhole/><strong>Authenticated boundary</strong><small>Row Level Security and server-only credential access</small></div><article><span>Server-only</span><h3>Connection secrets</h3><ul><li>GitHub access and refresh tokens</li><li>Paseo pairing capabilities</li><li>Credential-encryption keys</li><li>Administrative database access</li></ul></article></div></section>
    <section className="security-grid"><article><Database/><h3>Account isolation</h3><p>Supabase authentication identifies every request. Row Level Security limits operational records to their owning user, while secret tables deny browser access.</p></article><article><KeyRound/><h3>Encrypted credentials</h3><p>GitHub tokens and Paseo pairing capabilities are encrypted server-side with a versioned AES-256-GCM key before persistence.</p></article><article><RadioTower/><h3>End-to-end encrypted relay</h3><p>Paseo Relay lets durable workflows reach a paired daemon without exposing the daemon itself to the public internet.</p></article><article><Wifi/><h3>Optional Tailscale transport</h3><p>Direct Tailscale connectivity can coexist with Relay on the same logical host, matched by Paseo’s stable daemon identity.</p></article><article><Github/><h3>Scoped GitHub access</h3><p>The GitHub App is limited to repository metadata, contents, pull requests, and checks across installations you authorize.</p></article><article><Server/><h3>Isolated execution</h3><p>Each workstream receives its own Paseo workspace and Git worktree so concurrent agents do not share a working tree.</p></article></section>
    <section className="marketing-dark-band security-band"><div><ShieldCheck/><span className="marketing-kicker">Durable without being exposed</span><h2>Agents keep working; workflows reconnect only when needed.</h2><p>Durable workflow steps open short-lived Paseo connections, persist progress, close the connection, and resume after transient failures or deployments.</p></div></section>
    <section className="marketing-final-cta"><span>Connect your existing infrastructure.</span><h2>Keep the code private and the work visible.</h2><MarketingCta suffix={<ArrowRight/>}/></section>
  </main>;
}
