import type { Metadata } from "next";
import { ArrowRight, Cloud, Github, KeyRound, LockKeyhole, RadioTower, Server, ShieldCheck, UserRound, Wifi } from "lucide-react";
import { MarketingCta } from "@/components/marketing-shell";

export const metadata: Metadata = { title: "Security", description: "How Agent God Mode protects accounts and connections while repository source remains on your infrastructure." };

export default function SecurityPage() {
  return <main className="marketing-subpage"><section className="marketing-page-hero"><span className="marketing-kicker">Security and privacy</span><h1>Your code, infrastructure, and subscriptions stay under your control.</h1><p>Agent God Mode connects only to the GitHub repositories and Paseo hosts you authorize. It does not ingest, store, index, or analyze repository source; coding-agent CLIs perform that work on your own machine or company infrastructure.</p></section>
    <section className="security-boundary"><div className="marketing-section-heading"><span>Clear boundaries</span><h2>See the work without exposing the keys.</h2></div><div className="boundary-diagram"><article><span>Visible in Agent God Mode</span><h3>Workstream activity</h3><ul><li>Workstreams and branches</li><li>Plans and annotations</li><li>Timelines and questions</li><li>Review findings and status</li></ul></article><div><LockKeyhole/><strong>Protected access</strong><small>Signed-in accounts and encrypted connections</small></div><article><span>Kept private</span><h3>Credentials</h3><ul><li>GitHub authorization</li><li>Paseo pairing details</li><li>Provider sign-in sessions</li><li>Private network access</li></ul></article></div></section>
    <section className="security-grid"><article><UserRound/><h3>Private accounts</h3><p>Each signed-in account can access only its own workstreams, plans, hosts, and settings.</p></article><article><KeyRound/><h3>Protected credentials</h3><p>GitHub and Paseo connection details are encrypted and are not displayed after setup.</p></article><article><RadioTower/><h3>End-to-end encrypted Relay</h3><p>Paseo Relay connects to a paired host without exposing that host to the public internet.</p></article><article><Wifi/><h3>Optional Tailscale connection</h3><p>Use your private tailnet for direct browser-to-host access, with Relay available alongside it if you choose.</p></article><article><Github/><h3>GitHub metadata, not code ingestion</h3><p>The GitHub connection lists authorized repositories and coordinates branches, pull requests, and checks. Agent God Mode does not ingest, store, index, or analyze repository source through that connection.</p></article><article><Server/><h3>Isolated execution</h3><p>Paseo checks out the selected branch into an isolated workspace on your infrastructure. That is where agents read and change code.</p></article><article><Cloud/><h3>Credentialless AWS access</h3><p>Connected AWS accounts use short-lived OIDC and STS sessions. A unique external ID and scoped customer role prevent one connection from being used for another account.</p></article><article><ShieldCheck/><h3>Auditable infrastructure actions</h3><p>CloudFormation and Session Manager actions appear in your AWS CloudTrail history. Disconnecting removes app access; deleting the access stack in AWS revokes the customer role completely.</p></article></section>
    <section className="marketing-dark-band security-band"><div><ShieldCheck/><span className="marketing-kicker">Protected while agents work</span><h2>Your agents can keep working without an open tab.</h2><p>Agent God Mode records progress and reconnects to your Paseo host as work advances.</p></div></section>
    <section className="marketing-final-cta"><span>Connect your existing infrastructure.</span><h2>Keep the code private and the work visible.</h2><MarketingCta suffix={<ArrowRight/>}/></section>
  </main>;
}
