import Link from "next/link";
import { ArrowRight, GitBranch, Layers3, RadioTower, Workflow } from "lucide-react";
import { LifecycleDiagram, WorkstreamDiagram } from "@/components/marketing-diagrams";
import { MarketingCta } from "@/components/marketing-shell";

export default function MarketingHome() {
  return <main>
    <section className="marketing-hero"><div className="marketing-hero-copy"><span className="marketing-kicker">One Interface for Every Coding Agent</span><h1>Turn Plans Into Reviewed Pull Requests—Across Every Repository.</h1><p>Bring your Claude, Codex, Cursor, and other coding-agent subscriptions together through Paseo. Agent God Mode coordinates the work while your code and provider sign-ins stay on infrastructure you control.</p><div className="marketing-hero-actions"><MarketingCta suffix={<ArrowRight/>}/><Link className="marketing-secondary-button" href="/product">See How It Works</Link></div></div><WorkstreamDiagram/></section>
    <section className="marketing-lifecycle"><div className="marketing-section-heading"><span>One Controlled Lifecycle</span><h2>Every Agent Knows Its Role. You Control Every Gate.</h2><p>Move from a rough brief to a reviewed pull request without losing context between agents, repositories, or sessions.</p></div><LifecycleDiagram/></section>
    <section className="marketing-values"><article><GitBranch/><span>Isolated by Design</span><h3>One Branch and Workspace per Workstream.</h3><p>Parallel agents work without dirtying another branch or competing for the same sandbox.</p></article><article><Layers3/><span>Plans Are First-Class</span><h3>Capture, Revise, Annotate, and Sequence Work.</h3><p>Plan revisions replace the current version, while dependencies keep implementation in the right order.</p></article><article><Workflow/><span>Keep Work Moving</span><h3>Agents Continue When You Step Away.</h3><p>Return to one timeline with progress, questions, findings, and pull-request status up to date.</p></article></section>
    <section className="marketing-dark-band"><div><span className="marketing-kicker">Your Infrastructure, Your Subscriptions</span><h2>Paseo Brings the Agents Together Without Taking Custody of Your Code.</h2><p>Agent God Mode uses GitHub to list the repositories you authorize and coordinate branches, pull requests, and checks. It does not ingest, store, index, or analyze repository source. Paseo and your coding agents do that work on infrastructure you control.</p><div className="marketing-inline-points"><span><RadioTower/>Paseo Relay or Tailscale</span><span><GitBranch/>GitHub Metadata and Delivery</span></div></div><Link className="marketing-dark-link" href="/security">Explore Security<ArrowRight/></Link></section>
    <section className="marketing-final-cta"><span>Bring Order to Parallel Agent Work.</span><h2>One View From Idea to Reviewed Pull Request.</h2><MarketingCta suffix={<ArrowRight/>}/></section>
  </main>;
}
