"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Eye, GitBranch, ShieldCheck } from "lucide-react";
import appIcon from "../../../resources/icon.png";

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/auth/sign-in", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? "Authentication failed"); router.push("/"); router.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Authentication failed"); } finally { setBusy(false); } }
  return <main className="login-page"><section className="login-brand"><div className="login-wordmark"><img src={appIcon.src} alt=""/><strong>Agent God Mode</strong></div><div className="login-pitch"><span className="eyebrow">One clear view of every agent</span><h1>Move from idea to reviewed pull request.</h1><p>Plan, build, and review across every GitHub repository through your private Paseo infrastructure.</p><ul><li><GitBranch/><span><strong>Isolated workstreams</strong><small>One branch and one Paseo workspace per stream.</small></span></li><li><Eye/><span><strong>Plans you can shape</strong><small>Annotate, sequence, revise, and launch without duplicates.</small></span></li><li><ShieldCheck/><span><strong>Durable review loops</strong><small>Work continues when your browser is closed.</small></span></li></ul></div><small>GitHub and Paseo credentials are encrypted and server-only.</small></section><section className="login-panel"><form onSubmit={submit}><img src={appIcon.src} alt="" className="login-icon"/><span className="eyebrow">Welcome back</span><h2>Sign in to Agent God Mode</h2><p>Enter your email and password.</p>{error && <div className="banner error">{error}</div>}<label>Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={8} required/></label><button className="primary login-submit" disabled={busy}>{busy ? "Please wait…" : "Sign in"}<ArrowRight/></button></form></section></main>;
}
