"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Eye, GitBranch, ShieldCheck } from "lucide-react";
import appIcon from "../../../resources/icon.png";

export default function LoginPage() {
  const router = useRouter();
  const [mode, setMode] = useState<"sign-in" | "sign-up">("sign-in");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? "Authentication failed"); if (value.confirmationRequired) setNotice("Check your inbox to confirm your account."); else { router.push("/"); router.refresh(); } } catch (error) { setError(error instanceof Error ? error.message : "Authentication failed"); } finally { setBusy(false); } }
  return <main className="login-page"><section className="login-brand"><div className="login-wordmark"><img src={appIcon.src} alt=""/><strong>Agent Lens</strong></div><div className="login-pitch"><span className="eyebrow">One clear view of every agent</span><h1>Move from idea to reviewed pull request.</h1><p>Plan, build, and review across every GitHub repository through your private Paseo infrastructure.</p><ul><li><GitBranch/><span><strong>Isolated workstreams</strong><small>One branch and one Paseo workspace per stream.</small></span></li><li><Eye/><span><strong>Plans you can shape</strong><small>Annotate, sequence, revise, and launch without duplicates.</small></span></li><li><ShieldCheck/><span><strong>Durable review loops</strong><small>Work continues when your browser is closed.</small></span></li></ul></div><small>GitHub and Paseo credentials are encrypted and server-only.</small></section><section className="login-panel"><form onSubmit={submit}><img src={appIcon.src} alt="" className="login-icon"/><span className="eyebrow">{mode === "sign-in" ? "Welcome back" : "Create your account"}</span><h2>{mode === "sign-in" ? "Sign in to Agent Lens" : "Start using Agent Lens"}</h2><p>Use your Supabase email and password.</p>{error && <div className="banner error">{error}</div>}{notice && <div className="banner success"><Check/>{notice}</div>}<label>Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required/></label><label>Password<input type="password" autoComplete={mode === "sign-in" ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} minLength={8} required/></label><button className="primary login-submit" disabled={busy}>{busy ? "Please wait…" : mode === "sign-in" ? "Sign in" : "Create account"}<ArrowRight/></button><div className="login-switch">{mode === "sign-in" ? "New to Agent Lens?" : "Already have an account?"}<button type="button" onClick={() => setMode(mode === "sign-in" ? "sign-up" : "sign-in")}>{mode === "sign-in" ? "Create account" : "Sign in"}</button></div></form></section></main>;
}
